name: 'Semantic Version Bump'

on:
  push:
    branches:
      - main
      - master
      - develop
jobs:
  bump-version:
    name: 'Bump Version on main'
    runs-on: ubuntu-latest
    permissions:
      actions: read|write
      checks: read|write
      contents: read|write
      deployments: read|write
      id-token: read|write
      issues: read|write
      discussions: read|write
      packages: read|write
      pages: read|write
      pull-requests: read|write
      repository-projects: read|write
      security-events: read|write
      statuses: read|write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          major-wording: 'BREAKING CHANGE,MAJOR'
          minor-wording: 'feat,MINOR'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag created -  $NEW_TAG"
